### ISSUE TITLE
Frequent refresh problems

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#100]
Refreshing tabs using the in-app icon left of all the tabs sometimes leaves a blank tab (doesn't show all data it was showing a moment ago, plus stage updates made before the refresh).

This has been seen often in Chrome - I tried once in IE, same result; once in Firefox and that seemed fine.

The only way to get the data showing again is to do a hard refresh from the browser, but then you have to re-enter the tab you were just in because the default outcome of that hard refresh is always the first tab PreXCP.

**Comment by ben-garside** [comment]
This is a known issue, i will raise this as a bug

**Comment by VermaBSI** [comment]
The fix made to this for v1.3 UAT is now experiencing some faults - often refreshing a table within a tab produces the following error:

Data Tables warning: table id=tasks_team - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

And then a hard refresh from the browser has to be done, which effectively takes us back to the original usability problem.

**Comment by VermaBSI** [comment]
This happens frequently whenever refreshing generally - I tried also refreshing from the browser within an item's detail page.

**Comment by ben-garside** [comment]
Hi,

Could you please give me a list of actions that will reproduce this error, this will greatly assist in the fix. I have never come across this issue before :S

**Comment by VermaBSI** [comment]
Hi,

I believe I have provided two actions as examples, each in my two comments above. To re-iterate:
1. Refreshing a table/list within a tab (an Activity tab) using the in-app icon 
2. Refreshing from the browser when in an item's detail page (I think I was doing the re-collation test when I experienced this, but that was before actually hitting re-collate, so I think this is a general fault not specific to the test)

**Comment by ben-garside** [comment]
1. i am refreshing on multiple tabs in the activity tracker page, and i am unable to recreate the error message.
2. Same here, clicking refresh when in an item detail page is not causing an error.

@wanderingeagle could you also run the tests?

**Comment by VermaBSI** [comment]
It was happening a lot to me yesterday evening when I was trying to get as much testing done, and thought since you said you would be looking at this whole refresh and usability issue in more detail some point later, it would be useful to record any unwanted symptoms for your reference. If I come across it again I will personally show you.
