### ISSUE TITLE
Data retrieved for UPI by universal search not accurate

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#102]
I’ve noticed the stages data returned for a particular UPI searched universally at the top doesn’t match as it appears (and is searchable) within the tabs: e.g. try 30256178.

In the tabs PL7 for 30256178 exists at 30.00 (Assigned), not 10.15 (Unassigned) as indicated by a universal search of this UPI.

**Comment by VermaBSI** [comment]
There are more examples (e.g. 30329879 whose PL7 is actually published at 70.10) - the general case seems to be the universal search returns outdated data based on when the UPI first entered the system/was in Activity 10?

Sister PL8s are affected too.

**Comment by ben-garside** [comment]
Looks like the search functions are using the old audit tables, i will deploy a fix soon.

**Comment by ben-garside** [comment]
need to update the `allData` view to use ACT_AUDIT_2 tested in dev and works fine, only the issues with the PRD database is resolved i will make the changes

**Comment by ben-garside** [comment]
https://gist.github.com/ben-garside/7dd9c16a467abe646641

**Comment by ben-garside** [comment]
I have made the required change, can you confirm please @VermaBSI

**Comment by VermaBSI** [comment]
Thanks Ben, I've checked this out and it's working now.

Please could I request also that once results have been retrieved by a universal search, there is a 'go back' button or something that takes you back to the previous screen (whichever tab you had open) instead of having to re-navigate via the Activity Tracker option in the menu bar at the top? Feel free to add this as a low-priority requirement to deal with later as it's no major thing, but just mentioning now so I don't forget to later.

Thanks!
