### ISSUE TITLE
Sticky/non-sticky rules not being abided

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#104]
I am raising this as a separate issue further to issue #99.

The move from stage 20.10 to 20.20 I have configured as a non-sticky rule, but following the required refresh explained in issue #99, it stays in my CLAIMED list instead of appearing in the UNCLAIMED list.

Just adding another example to confirm (I will not be adding any further examples I come across as that would be annoying and you've probably got the message :) ):

The move from 20.20 to 70.00 for PL 8s is a non-sticky rule, but I just moved a load of PL 8s to 70.00 and they are still in that tab's CLAIMED list.

**Comment by ben-garside** [comment]
Fixed. there were some major errors with the methods of updating the rules and also the method in which sticky assignment is check and applied.

**Comment by VermaBSI** [comment]
Hi I've tested this quite a lot moving items through the system and am satisfied rules are being abided, thanks. There's still the need to refresh the tab when the rule is non-sticky for it to update properly in the UNCLAIMED list it moves into from CLAIMED, but that's part of a general known issue with the system.
