### ISSUE TITLE
Clicking an item UPI to open up its record fails

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#111]
Clicking an item UPI to open up its record fails in UAT v1.3, error message:

SQLSTATE[08001]: [Microsoft][ODBC Driver 11 for SQL Server]TCP Provider: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by ben-garside** [comment]
The connection to the CMS database server (and consequently the `colos` database) is currently not allowed on the UAT server, I have out the request in the IT Dev to make the required firewall changes, but until that is completed testing of the re-collation and viewing the item page cannot be tested.

emailed Yaqub with the following request on Mon 25/01/2016 @ 09:54:

> Hello Yaqub,
> 
> Could to following connection be allowed on the XCP UAT machineplease:
> 
> 10.103.109.37 [UK-CHXCP.oscar.local] -> 10.33.204.26 [BSI16VSS11CMS] (1433)
> 
> Thanks 
> 
> Ben

**Comment by VermaBSI** [comment]
This is now working.
