### ISSUE TITLE
Wording in pop-up for Action 'Add comment'

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#113]
The Action 'Add comment' is primarily to allow user to add TAT and cost data when moving to stage 20.10, however this worded as 'Editor's comments' in the pop-up which is misleading. 

Please change to term 'comments' as a more generic choice.

**Comment by ben-garside** [comment]
is this not just a configuration change?

http://uat.xcp.cs/actionmanager.php?id=1

**Comment by VermaBSI** [comment]
Yes, so it is, sorry. Have changed this in UAT now so it will copy over into PROD (right?)
