### ISSUE TITLE
Please add back complete directory path in email send to Innodata

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#115]
Please can the dated folder be added into the automatic email sent out to Innodata, e.g. highlighted in bold below:

Dear Innodata,
This is to inform you that a new batch has been transferred to Innodata\'s FTP site, for review for producing agreed XML outputs. Attached is a transmission sheet detailing each Material (identified by UPI) in the batch.
Please could you confirm receipt of these files and get back on an estimated turnaround time (TAT) and cost. Following this we will confirm whether work should proceed.
Notes:
Directory path: /TO INNO/_**2016-01-27**_
• Materials are batched into zip files according to a single Conversion Pipeline (indicated in the Batch ID and the column Conversion_Pipeline in the transmission sheet)
• Each Material in the zip file needs to be processed through that Conversion Pipeline 
• Details in the transmission sheet confirm the file types we have provided for each Material (see columns Source_File_Type) and the required XML output (based on Schema, see column Output_File_Type)
Many thanks

**Comment by ben-garside** [comment]
Due to the nature that the text is defined for the email, this is actually quite a bit of effort to achieve . Happy to do the work, but may i just suggest removing the line about the directory path?

**Comment by VermaBSI** [comment]
Hi Ben, you had originally configured it to include this information as per my original specification. Then it got lost somehow when the sending stopped and was re-fixed, but with some undesired changes (this and also email ID recipients). Innodata need to know where to find the files in the FTP, so it's important please. Many thanks!

**Comment by VermaBSI** [comment]
Hi Ben - why have you closed this? This wasn't in the emails in the send completed yesterday, I thought you said and we agreed in yesterday's meeting it would be a prioritized requirement to add in the next release?

**Comment by ben-garside** [comment]
did you do a UAT sent yesterday? as this has been added to the email as part of commit:[0495c36401e73d5345e97c0d12cb5a6e08453ced](https://onlinetechnologydevelopment.visualstudio.com/DefaultCollection/_git/XCP/commit/0495c36401e73d5345e97c0d12cb5a6e08453ced#_a=summary).

i will do another send this morning to confirm.

**Comment by VermaBSI** [comment]
Hi

I didn't get a chance to do a send test on UAT on Thurs because that requires your manual triggering when we say so, and you had left for the day by then. Plus I remembered you saying in our last meeting when I asked that this fix would not be done until the next UAT release, so wasn't expecting it yet. 

In any case, could I suggest please that the person who opens a bug should be the one to close it specifically following their testing, just so we avoid confusion.

Thanks

**Comment by hendersm** [comment]
In the interest of not holding up today's deployment, I think we should recheck this once 1.3 is live and we have a live send. If there is still an issue, then we could look at an independent fix for it or include it in the planned 1.4 release.

Matt

**Comment by ben-garside** [comment]
@VermaBSI can this be closed?

**Comment by VermaBSI** [comment]
See Matt H's comment above.
(My understanding was to leave it open until confirmed as fixed in live.)

**Comment by hendersm** [comment]
Does this need to be closed to deploy 1.3? If yes, then we can close it and re-test once live. In no, then deploy and we’ll re-test on the next send.

**Comment by ben-garside** [comment]
ideally i would like all 1.3 milestone tickets closed. But it really doesn't matter, was going for completeness.

Will start the deploy.

**Comment by VermaBSI** [comment]
This happened right in the last live send, thanks
