### ISSUE TITLE
pseudo stream IDs should not be in tracker

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#116]
All items that failed stream allocation (Stream ID >= 90) should not be in activity tracker.

This means that the `activity.data` API needs its SQL changing (this issue came from the death of the `allData` view in the database).

**Comment by ben-garside** [comment]
updated SQL in both `activity.data` and `activity.count` API to exclude any item with a stream id in the pseudo range (<= 90)

**Comment by VermaBSI** [comment]
As per my last comment to #117 , this looks done to me.
