### ISSUE TITLE
in app inclusion should fail on allocation fail

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#117]
When adding an item via the `includecontent` page the system should fail if the content could not be allocated a pipeline (a pseudo pipeline is assigned).

Currently the system is then trying to collate content etc. meaning that the item is placed in the audit (00:01).

**Comment by VermaBSI** [comment]
I tried this again with an FDA UPI 30338078 and the system failed with message:
    Stream ID could not be determined (96)
The UPI also did not appear in any tab and a global search for it produced result:

Results for '30338078'

PL96 COMPLINAV
XCP9226379 | 30338078 | N/A | Unassigned
Class II Special Controls Guideline. Gastrointestinal Microorganism Multiplex Nucleic Acid-Based Assays for Detection and Identification of Microorganisms and Toxin Genes from Human Stool Specimens. Guideline for Industry and Food and Drug Administration Staff
