### ISSUE TITLE
Change to Innodata email recipient list

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#119]
Hi Ben,

Very sorry to have to ask for yet another change to the recipient email IDs but this time Innodata have specifically requested this for send notifications so they can respond more quickly with TAT and cost estimates:

Please could the recipient email ID list for notifications FOR PIPELINES 1-7 ONLY (not for PIPELINE 8) be changed to the one and only **BSI-Innodata-Team@innodata.com**

I am flagging this because it is neither an enhancement nor new feature request - it is just an important change to an existing parameter that needs to be made asap.

Thank you

**Comment by ben-garside** [comment]
this change has been made via a hotfix and is live on the production server

**Comment by VermaBSI** [comment]
Thanks Ben
