### ISSUE TITLE
Batch data not being correctly added in LIVE

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#126]
I would have raised this by re-opening original issue for adding BATCH ID when sending an item, but that seems to have disappeared off GitHub.

The last Live send done on 08/02/2016 following the release of v1.3 did not add batch data correctly:

Each item's detail page (see list of items below) shows its **UPI** as '**Innodata_Batch_ID**' added in **Item Data** not in Batch Data. 

It should show the **batch ID** as '**Innodata_Batch_ID** under **Batch Data**.

XCP2772216  30122247
XCP9397535  30315341
XCP0487734  30289935
XCP7422935  30295073
XCP3166080  30298221
XCP3226246  30301930
XCP0534407  30301933
XCP6879807  30303011
XCP7994577  30321467
XCP2921239  30289935
XCP2335649  30295073
XCP4602739  30298221
XCP1449166  30301930
XCP2674503  30301933
XCP4300684  30303011
XCP2909824  30315341
XCP5249096  30321467

**Comment by VermaBSI** [comment]
I've tested this with the following success and failure outcomes:

**1. Successes:**
Adding TAT and cost data to an item updates all items belonging to the same Batch ID (determined at sending stage).

I.e. if (item A) + (one or several item Bs) both belong to (batch C) then updating item A with TAT and cost data will update for all item Bs too.

**2. Failures:**
The system doesn't know that any item B in the above scenario already has been given TAT and cost data via item A, so when you move any item B to stage 20.10, it unnecessarily asks for TAT and cost data again. This also means you can overwrite TAT and cost data for all items in the batch every time you update an item B - that is, if you were to re-enter TAT and cost instead of just closing the Action without entering anything in.

Ideally, once item A has been moved to 20.10 by entering TAT and cost data, all item Bs should update to stage 20.10 with the same TAT and cost data automatically. Would this be possible?

I leave it up to you if you want to close this and raise as a new issue?

**Comment by ben-garside** [comment]
Hi,

If you want the system to check if data has already been entered you will need to check the `Prefill?` box in the action set up (`Data Settings` section). Currently the action(i think) you are referring to (id 1 - Add TAT and cost) it has not been ticked so it is going to ask for it with an empty field.

Worth noting that #71 will also help with this.

Can you try again after setting the action up and let me know if it is still an issue?

**Comment by VermaBSI** [comment]
Okay this has worked now, in that the same data entered via item A shows up in the Action pop-up for every item B that you push to 20.10 (so closing).

However, it seems unnecessary for the TAT and cost data Action to pop-up as if the system is asking for it again, for progressing every item B to 20.10, once that data has already been set via item A for the entire batch. So I will raise another requirement around this to scope at some point later.

But otherwise good to get to this point :)

**Comment by VermaBSI** [comment]
i.e. the Action is still not really being 'skipped' as per #71 requested.

**Comment by VermaBSI** [comment]
Sorry Ben - in case there is any more you could do to effect a genuine skipping of the Action so it doesn't even show up for every item B, I am just leaving this open.

**Comment by ben-garside** [comment]
Closing this ticket as it is not about skipping actions.

Skipping is handled in #71 which is in release 1.5.

**Comment by VermaBSI** [comment]
O sorry, for some reason I thought #71 was a one you had already dealt with

**Comment by VermaBSI** [comment]
With the release of v1.4 to Live this issue has resurfaced:

http://xcp.cs/item.php?xcpid=XCP9127119
http://xcp.cs/item.php?xcpid=XCP9705810

**Comment by ben-garside** [comment]
These batch ids were set before the fix was put in place  (15-02-2016)

**Comment by VermaBSI** [comment]
O right, apologies.
