### ISSUE TITLE
After the _real_ send, items should NOT remain CLAIMED

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#129]
After the _real_ send, items should NOT remain CLAIMED as they currently do, but should become UNCLAIMED at stage 20.00

**Comment by ben-garside** [comment]
The current stagemanager settings are that it should remain assigned, please correct these and try again.

#### Ruleset 1:

![image](https://cloud.githubusercontent.com/assets/9353593/13052275/dfc3482c-d3f5-11e5-9c2f-d3feab43ad00.png)

#### Ruleset 2:

![image](https://cloud.githubusercontent.com/assets/9353593/13052288/ee73e750-d3f5-11e5-8e44-35dc2e781349.png)

**Comment by VermaBSI** [comment]
O I didn't think these stage rules worked when the system automatically moves items across stages? 

And the rule for this would be where the destination would be 20.00 from 10.20: I've changed this to non-sticky, will now do another test send...

**Comment by ben-garside** [comment]
Yes, sorry screenshot-ed the wrong one. Yes all automatic transfers should follow the rules in the `stageManager`. Thanks, let me know how it goes.

**Comment by VermaBSI** [comment]
Hi - tried this again (XCP IDs below), but the system's automatic push to 20.00 is still sticky.

XCP9711794_30230633
XCP7842403_30197569
XCP4581113_30177594
XCP0134403_30055602

Doesn't look like stage rules are applicable to automated stage progressions, i.e. like for the 10.19 to 10.20 case which you fixed.

**Comment by ben-garside** [comment]
10:19 -> 10:20 are set at sticky assignment:

![image](https://cloud.githubusercontent.com/assets/9353593/13077851/4a759ec8-d4b3-11e5-8a38-f2a09e4c991d.png)

**Comment by VermaBSI** [comment]
I am talking about the move from stage 10.20 to 20.00 not the move from 10.19 to 10.20 as you have shown here (you've screen-shot the wrong one twice now).

**Comment by ben-garside** [comment]
Regarding the PL8s (XCP7842403 and XCP4581113):

![image](https://cloud.githubusercontent.com/assets/9353593/13078590/f6579b84-d4b7-11e5-984a-3a2761d3c2b6.png)

The others have now been fixed.

**Comment by VermaBSI** [comment]
Thanks.  I will do another test send some point this week.

None of the XCP IDs I listed above are PL 8 s, but thanks anyway.

**Comment by ben-garside** [comment]
FYI:
![image](https://cloud.githubusercontent.com/assets/9353593/13079316/928c3d40-d4bb-11e5-8b3f-7ed2327f59ed.png)
![image](https://cloud.githubusercontent.com/assets/9353593/13079236/1c05f15c-d4bb-11e5-9fe8-be32b73c08ce.png)
![image](https://cloud.githubusercontent.com/assets/9353593/13079271/509e9e32-d4bb-11e5-8077-526c4d313056.png)

I have deployed a fix to UAT, so please try again and let me know.

CHeers

**Comment by VermaBSI** [comment]
Whoops was looking at the UPIs, sorry. I really shouldn't look at these while I'm in a task! Which is why I'll test later too :)

**Comment by VermaBSI** [comment]
This worked, closing this now
