### ISSUE TITLE
drop down not working if unclaimed then claimed again

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#132]

**Comment by VermaBSI** [comment]
Hi, this one is still not really working (thanks for noticing this):

I tried un-claiming and then claiming again an item each at 20.10, 40.00, 70.10. You always have to refresh the tab or exit and re-enter the tab to see the drop down for the item you just claimed again.

**Comment by ben-garside** [comment]
Thanks for that. I will have a look in to what  the problem is.

**Comment by ben-garside** [comment]
the css class was not being removed as part of the unassign() method. This has now been fixed

**Comment by VermaBSI** [comment]
I am afraid I am still experiencing the same problem as per my previous comment.

**Comment by VermaBSI** [comment]
Now working, thanks.
