### ISSUE TITLE
Update function in Edit Action does not work

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#135]
E.g. see any Edit Action page: http://uat.xcp.cs/actionmanager.php?id=1

If you make any changes to the fields and press any Update button, the change doesn't stay after you exit and re-enter the page. So it's not updating.

**Comment by VermaBSI** [comment]
Just adding Matt H so he's aware of all issues for next XCP meeting: @hendersm

**Comment by ben-garside** [comment]
fix in 1.5WIP

**Comment by VermaBSI** [comment]
Hi, I tried making edits to this action http://uat.xcp.cs/actionmanager.php?id=1 but it still isn't saving after you press Update...

**Comment by VermaBSI** [comment]
Action rules are now saving upon update, thanks.
