### ISSUE TITLE
LIVE: 'Just mine' vs. 'All Users' filter not working

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#136]
Filtering for 'Just mine' in the dropdown list filters above the tabs is for some reason not working now in Live. The numbers and lists stay the same as for the filter 'All Users'.

**Comment by ben-garside** [comment]
I am unable to recreate this issue:

![image](https://cloud.githubusercontent.com/assets/9353593/13917601/d094ba32-ef59-11e5-99e3-8aa62beb2de3.png)

**Comment by VermaBSI** [comment]
This has been working recently - perhaps it was a refresh problem experienced before, Am closing, thanks.
