### ISSUE TITLE
LIVE (v1.4): submitting comments in item detail page

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#138]
LIVE (v1.4): submitting comments in an item detail page doesn't work - after pressing submit comment, the comments tab doesn't update with the text written in the 'Add a new comment' window.

**Comment by VermaBSI** [comment]
Just adding Matt H so he's aware of all issues for next XCP meeting: @hendersm

**Comment by ben-garside** [comment]
resolved, please test @VermaBSI

**Comment by VermaBSI** [comment]
This works in Live and current UAT v1.5, many thanks.
