### ISSUE TITLE
LIVE (v1.4): Action 'Add TAT and cost' not working

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#139]

**Comment by VermaBSI** [comment]
The Action 'Add TAT and cost' (see http://xcp.cs/actionmanager.php?id=1) has been correctly configured as far as I can tell. But trying to perform the action for moving items currently at 20.05 to 20.10, is running an error. The item IDs are below. They were sent to Innodata yesterday, and have correct batch data added in their item detail pages, so can't see why there's a problem.

**Comment by VermaBSI** [comment]
XCP9066229_30314045
XCP4305821_30314057

Just adding Matt H so he's aware for next XCP meeting: @hendersm

**Comment by ben-garside** [comment]
what is the error you are getting please?

**Comment by ben-garside** [comment]
@VermaBSI i have moved these to be two different fields in the add TAT and EST action, let me know if you are still having issues in UAT

**Comment by ben-garside** [comment]
sorry, i see it was not an error in UAT... ignore me :S

**Comment by VermaBSI** [comment]
Yeh I am hoping I won't see this once v1.5 is pushed to Live...so we can look to closing this thereafter

**Comment by ben-garside** [comment]
I have split it in LIVE as well.

**Comment by VermaBSI** [comment]
Thanks, this split makes sense.
