### ISSUE TITLE
Can't put a UPI back a stage

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#14]
If a user sets a stage for a UPI (e.g. 10.12) but then decides they want to set it to an earlier stage (back to 10.10 - e.g. if they want to put back out of the list of potential/pending sends after conferring with the Product Manager) there seems no way of doing this. The only change of stage allowed is progressive - so to 10.20, but then this sets the UPI for automated sending, which we don't want. 

(Another likely example - to come up - would be moving from stage 40.10 to 30.25).

Even if you CLAIM, UNCLAIM and the re-CLAIM, the originally set stage at CLAIM (e.g. 10.12) continues throughout. If something is UNCLAIMED should it not revert to the earliest minor stage within that tab/major stage (10.00)? i.e. since the point of CLAIMING is to deal / start again with the progression of the chosen UPI onwards from stage 10.00

**Comment by ben-garside** [comment]
This needs to be addressed as a config change. A meeting needs to be arranged to review these settings.

As for the claiming and unclaiming, it does not have any impact on the stage of an item only if it is claimed by an individual user of open to be actioned by someone else. Unclaiming it will just release it back to the team. If this is not the desired effect it will need to be agreed by the team and submitted as a feature change request.

**Comment by VermaBSI** [comment]
Hi Ben,

Okay thanks – do we have an XCP meeting scheduled this week (Adam)?

Many thanks,

Varun Verma
Online Production

T: +44 20 8996 7352
varun.verma@bsigroup.com<mailto:varun.verma@bsigroup.com>


[cid:image002.jpg@01D0DA86.DF79D200]
BSI Group, 389 Chiswick High Road, London, W4 4AL, UK
bsigroup.com<http://www.bsigroup.com/> | Twitter<https://twitter.com/bsistandards> | LinkedIn<https://www.linkedin.com/company/bsi>
[cid:image004.png@01D0DA86.DF79D200]

BSI Standards Limited is a member of BSI Group and is incorporated in England by Royal Charter with its principal office at 389 Chiswick High Road, London, W4 4AL, United Kingdom
Please consider the environment before printing this email

**Comment by ben-garside** [comment]
@afproductions is going to set one up #16 at some point
