### ISSUE TITLE
Setting stage 10.20 moves to CLAIMED list in Conversion tab

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#15]
When a UPI is set to stage 10.20 (Ready to Send - triggering its FTP), I understand it is automatically moved to stage 20.00 in the Conversion tab once the system has successfully made the transfer. That's good, but should it not be moved to the UNCLAIMED list in the Conversion tab instead of the CLAIMED list? 

I understand the sense of the CLAIMED and UNCLAIMED duality in each tab is to allow manual choosing of UPIs for stage progression (or regression), which makes sense in the context of several users sharing workload. If the system will automatically move a UPI into a CLAIMED list within a major stage / tab then the point of this setup seems lost to me (?)

**Comment by ben-garside** [comment]
Hey,

This is more of a configuration issue, and needs to be talked about with the flow config. I agree it should be released for any user to pick up once it has been sent. 

The claiming of an item as the stage changes is handled in the configuration, every rule can either persist the owner or release it back to the team.
