### ISSUE TITLE
Stop processing CEN XML

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#18]
We need XCP to stop processing CEN source XMLs it manages to find for any Materials (i.e. BS ENs, even sometimes BS EN ISOs).

The only XML source files XCP should be finding in its collation process is from ISO (i.e. for ISO based Materials).

Would it be possible to get this fixed for the next release of XCP please?

**Comment by ben-garside** [comment]
@afproductions, @odeclas can you validate this change please?

Thanks.

**Comment by odeclas** [comment]
Yes. CEN XML is currently not production ready, so where CEN provide the body content please treat it as a full document conversion.

**Comment by ben-garside** [comment]
need to stop the collation of all XML content sourced from CEN. This includes AM and NW, so all CEN pl4 will become pl2

**Comment by ben-garside** [comment]
Currently we have no idea what SDO an item is when its being processed in the collation/allocation job, need to pull that data in to the job to allow the is CEN check before looking for XML content

**Comment by VermaBSI** [comment]
See latest comments in #25 too, as there may be some complications to work through here.

In the meantime I will spot any p4 CEN XMLs whilst checking items for sending and arrange with  you for their re-assignment as p2.

**Comment by odeclas** [comment]
I think the ticket requirement has been met, in that CEN XML (generally) has stopped being processed. If we need to raise a specific exception - as per #25, then that should be a separate ticket. Closing on that basis.

**Comment by VermaBSI** [comment]
Not sure if Ben has finished the fix for this (this issue no. was not in the resolved list as part of the last beta release).

Otherwise I haven't seen any ENs come in other than p2, so that suggests for the most part (i.e. for EN based stuff) CEN XML is no longer being processed.
 
But so as long as CEN XML is getting through for EN ISO cases (as happened for an item sent to Innodata a little while back), someone has to manually check for CEN XMLs in EN ISO collations.

**Comment by ben-garside** [comment]
Waiting for feedback from @afproductions in regards to the CDer etc.
