### ISSUE TITLE
Integrate action framework in to tracker

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#19]

**Comment by odeclas** [comment]
I don't really understand what this issue is describing - could you elaborate?

**Comment by ben-garside** [comment]
Not an issue, but a previous requirement. This is for the creation of the functionality to have action within a workflow (for example add data to an Item)

**Comment by odeclas** [comment]
In so far as I can see data being added to ITEM_DATA as part of an action in a workflow (activity transition) I am closing this....
