### ISSUE TITLE
Some feed 4 items not showing in XCP

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#21]

**Comment by ben-garside** [comment]
some FEED4 items have been allocated PL93 (Unknown feed id)

**Comment by ben-garside** [comment]
The following where incorrectly allocated:

XCP2802599
XCP0188681
XCP9868209
XCP1022167
XCP0855700
XCP9601943
XCP6817058
XCP7315005
XCP0662411
XCP7342350
XCP3069575
XCP0796100

Looks like it was just a legacy issue, i am running the collation process now to see if they get picked back up

**Comment by ben-garside** [comment]
All PL8 should now be available. @VermaBSI can you validate this please.

**Comment by VermaBSI** [comment]
Hi, thanks - all are there and I have set all to 10.20

Please could you also change 30326239 to pipeline 2 from 4, so I can include it in this send.

Please could you also let me know if you think finding that lost UPI 30320346 is easily do-able today to include in this send to?

Thanks :)!

**Comment by ben-garside** [comment]
these are covered in #22 and #23

**Comment by VermaBSI** [comment]
Hi Ben,

I take it then that you are still dealing with these then, so am I best to leave them out of this send today?

Many thanks,

Varun Verma
Online Production

T: +44 20 8996 7352
varun.verma@bsigroup.com<mailto:varun.verma@bsigroup.com>


[cid:image002.jpg@01D0E000.E14FCE70]
BSI Group, 389 Chiswick High Road, London, W4 4AL, UK
bsigroup.com<http://www.bsigroup.com/> | Twitter<https://twitter.com/bsistandards> | LinkedIn<https://www.linkedin.com/company/bsi>
[cid:image004.png@01D0E000.E14FCE70]

BSI Standards Limited is a member of BSI Group and is incorporated in England by Royal Charter with its principal office at 389 Chiswick High Road, London, W4 4AL, United Kingdom
Please consider the environment before printing this email
