### ISSUE TITLE
I need you to change 30326239 to pipeline 2 not 4, so I can include it in this send

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#22]
from VV

**Comment by ben-garside** [comment]
from VV

**Comment by ben-garside** [comment]
@VermaBSI which files need to be included in the zip for this?

**Comment by VermaBSI** [comment]
Pipeline 2 - so just the source PDF.

**Comment by ben-garside** [comment]
XCP4477629 is now set at a STREAM2 please confirm the details are correct @VermaBSI

Cheers
Ben

**Comment by VermaBSI** [comment]
Confirm it's correct thanks
