### ISSUE TITLE
UPI 30320346 that dropped out between resetting the collation lists

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#23]
FROM VV

**Comment by ben-garside** [comment]
XCP3617027 is now back in the system, please validate this @VermaBSI

**Comment by VermaBSI** [comment]
Yes it is thanks - but it's pipeline 8 isn't.

All pipeline items except for pipeline 1 need to come in as pipeline 8 items too.

**Comment by ben-garside** [comment]
XCP3617027 is STREAM_ID:2

http://xcp.cs/item.php?xcpid=XCP3617027

**Comment by VermaBSI** [comment]
Yes that's correct. It needs to feature as a stream 2 and 8 item.

**Comment by ben-garside** [comment]
I am not sure what you are asking here. there are two items for 30320346:

 - XCP3617027 stream: 2 current stage: 10:10 (assigned to you)
 - XCP6124173 stream: 8 current stage: 20:00 (unassigned)

what do you require doing?

**Comment by VermaBSI** [comment]
Sorry Ben, didn't realise pipeline 8 XCP6124173  was in the Conversion tab (so already sent).

I have sent all I have wanted to 10.20. However, I was wondering if a few of the ISO-based pipeline 2 items could be set to pipeline 4 (I have downloaded the source XMLs from ISO that XCP did not manage to find).

I realise assigning everything XCP could to pipeline 4 is not happening yet, so I am conscious of having to step in manually to find what it didn't. The reason being it does significantly speed up Innodata's turnaround time if we can utilise ISO's XML where available. 

The UPIs that should ideally be pipeline 4 (not 2) are: 30156028, 30263390, 30320346, 30326239.
I have the ISO XMLs for these to provide, would doing this be a big pain?

**Comment by ben-garside** [comment]
Can you please keep comments on an issue on topic. 

If the additional comments here are related to another issue please post there, if not please can you raise as a new issue https://github.com/ben-garside/XCP/issues/new

If you have other requests or issues please add them as a new one to allow things to be tracked.

**Comment by VermaBSI** [comment]
Hi, this can be closed now :)
