### ISSUE TITLE
add action to Flow Manager

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#24]

**Comment by ben-garside** [comment]
the flow manager needs action to be settable in the editing form

**Comment by odeclas** [comment]
I have successfully added an Action to the Flow Manager, although I have requested some extra work in issue 54. 

I have not been able to test the added Action, because of issue 55.

**Comment by odeclas** [comment]
Stuck on issue 55.

**Comment by ben-garside** [comment]
This is to add the field 'Action' in to the flowManager page to allow users to view selected action and select one.
