### ISSUE TITLE
Pipeline 2 items that should ideally be Pipeline 4

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#25]
This is an ongoing issue with XCP.

ISO XMLs available from ISO's site are not being picked up internally, so some UPIs are not being assigned pipeline 4.

Currently the following should ideally be pipeline 4 (I have their ISO XMLs downloaded to provide):

30320346
30326239
30263390
30156028

**Comment by ben-garside** [comment]
@VermaBSI I will remove the allocation and collated files for these. Could you please put the newly collated zip file (the ones you DL'd) in the XML archive. I can then do a re-index and the system should then allocate the right pipeline and collate the correct files (I hope).

**Comment by ben-garside** [comment]
30320346 - XCP3617027 - pipeline changed|files removed
30326239 - XCP4477629 - pipeline changed|files removed
30263390 - XCP4754429 - pipeline changed|files removed
30156028 - XCP9952620 - pipeline changed|files removed

**Comment by ben-garside** [comment]
@VermaBSI I have moved them all to 10:15 hope thats OK

**Comment by VermaBSI** [comment]
Hi Ben, I have manually collated these zips as pipeline 4s, named by UPI - which XML archive are you talking about for depositing them in?

10.15 is fine. Once the collations are picked up I will claim them and set them for 10.20 for another send.

**Comment by ben-garside** [comment]
Very good question about the file location :expressionless: somewhere in [[\\chi-cl-fp03\PDFarchive\XML]] but I don't know which sub-folder they would go in.. I guess RAW?

The collation process will automatically set them to 10:20 if they are successfully collated, so they should just appear ready for you to claim them.

**Comment by VermaBSI** [comment]
Okay I've put them in Z:\RAW\ISOSTS\ISO so let's see if that works. I included the PDF source in each UPI zip alongside the ISO XML, perhaps incorrectly.

**Comment by ben-garside** [comment]
TBH I have no idea what that will do, it will either be ignored or we will end up with a duplicate.

**Comment by ben-garside** [comment]
So the PDF file caused an error... but the good news is is that it has now allocated the correct pipeline, i will amend the zips and re collate the content.

**Comment by VermaBSI** [comment]
Thanks Ben, sorry about the PDF error

**Comment by ben-garside** [comment]
this is related to #31 and needs that to be fixed first.

**Comment by ben-garside** [comment]
@VermaBSI I have re processed them all and two of them have worked spot on, however there is still issues with the other two:

I think we just need to rename the zip file that you manually sourced to relate to the correct ISO material (not the BS) for **XCP4754429** (30263390) the ISO material for that project (2012/01171) is 30263392 so the system will be looking for a file called 30263392.zip with the ISO XML in it.

As for **XCP9952620** it is a AM so i believe we are looking for the XML version of the previous BS version which would be 30112807 which we don't have so it would correctly be a pipeline 2 and only the published PDF is required (this is based on the way the allocation is currently set up)

30320346 - **XCP3617027** (collated ISO 30320348.zip) - in XCP
30326239 - **XCP4477629** (collated ISO 30326366.zip) - in XCP
30263390 - **XCP4754429** (no ISO 30263392.zip file)
30156028 - **XCP9952620** (no ISO 30112807.zip file)

**Comment by VermaBSI** [comment]
Hi Ben,

I have renamed UPI zip 30263390 to 30263392 in

Z:\RAW\ISOSTS\ISO

(But how come it could find the ISOs for the two successful occasions named by BS UPI)?

Regarding 30156028 - this is an AM and XCP seems correct to treat it that way, but looking at it, the only reason it is an AM is because the date in its Standard ID has been corrected - and then there is no '+AX' designation in its Standard ID. In that way, the ISO XML is true to it in terms of body content, save for this date change in a few places, Therefore please could you assign it pipeline 4 using the ISO XML I sourced, we will deal with editing the few date incidents in the XML afterwards.

Thanks!

**Comment by ben-garside** [comment]
XCP9952620: This is going to cause a problem, as it means that either we need to change the rules (as in this case XCP has done exactly what has been asked of it), or need to allow a user to manually change the pipeline and resupply the files (@odeclas seemed against this idea). I am worried about doing a one off bending of the process rules for something that might come up again and perhaps a solution needs to be thought about?

**Comment by VermaBSI** [comment]
Hi Ben,

Apologies if I've got this wrong - but I thought yesterday we were talking about configuring to allow the option to manually change any XCP item in terms of pipeline, to avoid you having to alter in the database. i.e. I would source the ISO XML for what I wanted, re-package and deposit in the designated location, and then this 're-assignment' would be picked up in the next collation run?

The option for this manual intervention I think is the only viable one - because the nature of what we are dealing with means every so often there seems to be small silly cases like this one, which I don't think we can, or should, adjust/bend XCP process rules for to accommodate :)

Hope that makes sense.

**Comment by VermaBSI** [comment]
Hi Ben,

Further on this: there are some more UPIs to add.

Everything currently set at '10:15 - Published - Query package' in the CLAIMED list in the Collations Tab (PROD env) needs to be assigned pipeline 4.

That includes 30156028 mentioned above. I can no longer see 30263390 mentioned above in the system anywhere.

 Like before, I have manually sourced their ISO XMLs for supply, so let me know what you want me to do with those and when.

Thanks :)!

**Comment by VermaBSI** [comment]
Sorry just to add - you will see 30247606 is set at 10.15 too, but that is for a different reason.

To be clear, the updated list of UPIs of concern for this are:

30292271
30295065
30295068
30156028
30263390 (no longer in the system apparently)

**Comment by ben-garside** [comment]
Only 13 days late on my reply... sorry :confused:

30263390  had been claimed so you were unable to see it. I have assigned it back to you so it should be in your list again.

Have the files been placed correctly named in the XML archive? If so I will reprocess them and they should be reallocated correctly.

**Comment by VermaBSI** [comment]
Yes I've downloaded them. Do they need to be named by the UPI we give to raw ISO Material (I have no idea what they would be - perhaps Adam F would know the quickest way to get this).

As per my comment in #26, more have come in since that I need to download. 

Will get them all correctly named and placed later in the week.

Thanks
Varun

**Comment by ben-garside** [comment]
Yeah they will need the relevant UPI for the ISO material in the project.  Quickest way to find it is to look in SAP.

**Comment by VermaBSI** [comment]
I'd knew you'd say SAP! I'll just check if Adam F can retrieve a load for me in one go, to avoid doing one by one in SAP :)

**Comment by ben-garside** [comment]
if you have a list of Project numbers or UPIs I will get them for you. DO you not like SAP?

**Comment by VermaBSI** [comment]
It's just I'd rather not have either you or me do this checking one record after another in SAP, that's laborious considering this will be an on-going issue, i.e. we'll have to keep on doing this until it's fixed. If we could retrieve ISO UPIs for several BS-adopted UPIs in one go/click that would be better. We've got until Friday to get them all re-assigned, etc. and anymore that will come in, so will confer with Adam F when he's back in.

**Comment by ben-garside** [comment]
OK, i was just going to run an SQL query against the DWH not manual at all, would take 2 mins, but if you want to wait for AF... thats up to you :smile:

**Comment by VermaBSI** [comment]
Right, okay, I thought you might, wasn't sure - which is fine, what I was after :). I haven't done SQL before.

The list of UPIs are all those set at 10.15 pipeline 2 in Collation in PROD (CLAIMED list). I'll get round to downloading their ISO XMLs later in the week. Thanks!

**Comment by ben-garside** [comment]
30260135	2012/00466	30291720	ISO 13397-5:2015
30263390	2012/01171	30263392	ISO 4823:2015
30047368	1995/04982	30041349	No Description (Temp)
30264426	2012/01348	30264427	ISO 10865-2:2015
30295065	2013/03596	30297206	ISO 16672:2015
30295068	2013/03597	30297205	ISO 16671:2015
30297755	2014/00333	30298218	ISO 16408:2015
30329680	2015/02242		Only has a CEN material
30292271	2013/02990		Only has a CEN material
30156028	2005/00089		Only has a CEN material

**Comment by ben-garside** [comment]
The three at the bottom do not have ISO materials in their projects, have no idea why :confused:

**Comment by VermaBSI** [comment]
Thanks! Yes, sometimes source EN ISOs originate as CEN not ISO (for some reason :/) - so need to check there is no other pre-BSI UPI for these (e.g. CEN UPI?).

Question: so if SAP has ISO UPIs registered for most of these, how come their ISO XMLs are not in our internal system for XCP to discover? Wouldn't an ISO UPI in SAP suggest ISO source files are in? :S

**Comment by VermaBSI** [comment]
Just clarifying my point above:
Sometimes EN ISOs do not have an ISO-only title page, just the CEN title page. I am thinking this might indicate CEN as 'source' - i.e. BSI have sourced in CEN files for these Materials only, and not the ISO source files available further upstream (which I can otherwise retrieve manually from the ISO site). 

Thus the non-existence of ISO source Material and UPI for these ISO-based items?

@afproductions - Adam F would you know more about this (see comments above too)? I may be completely barking up the wrong tree...

**Comment by VermaBSI** [comment]
Hi Ben - just a note to say I will wait until Friday before downloading the ISO XMLs for identified UPIs above, in case more come in through XCP. On Friday then you'll need to re-assign a bunch of p2s to p4s as part of the 4-5pm send. If that's too tight I'll have the ISO content downloaded and in place by the end of the morning.

**Comment by VermaBSI** [comment]
Hi Ben,

So collation runs 10am every day - that's fine, that doesn't need changing.

I will get all XMLs downloaded for p2 ISOs and in place later today, so hopefully they will be re-picked up as p4s tomorrow 10am - I am just waiting on Adam F to advise on how to deal with those BS UPIs missing ISO UPIs.

**Comment by afproductions** [comment]
Just for the record, the 3 projects that don't have ISO UPIs are renumbering AMDs (BS ISO to BS EN ISO), so the ISO will be attached to the previous BS ISO project. But if these are in a product (guessing CN) then I would have thought, could be wrong, that we would already have the the BS ISO XML, so just need to insert the EN content

**Comment by VermaBSI** [comment]
Great, thanks for that - I forgot I knew one of them was a renumbering AMD! I will investigate the previous BS ISO projects. Is there a quick way I/you could get those previous UPIs, apart from looking manually in SAP? Since I'd need to name the BS ISO XMLs I find with them for picking up as p4.

**Comment by VermaBSI** [comment]
Okay I've finished downloading all 12 ISO XMLs and renaming with their pre-BS UPIs I looked up in SAP. One I couldn't find XML for even manually, so I've approved as a p2 (set to 10.20).

That was a headache! Fingers crossed I selected the right pre-BS UPIs XCP will be searching for from all the SAP entries, so they will be picked up as p4 outputs when the collation runs tomorrow.  

Also - don't their existing entries in XCP need to be first removed Ben, to be picked up as 'new' collations? 

I placed the ISO files in here: Z:\RAW\ISOSTS\ISO

**Comment by VermaBSI** [comment]
Hi guys - this didn't work, XCP has made no collations today as notified, Could I just check please why not and what needs to happen today so I can get these sent as p4s today please?

**Comment by VermaBSI** [comment]
@odeclas

**Comment by ben-garside** [comment]
You are correct, this did not happen as a manual database change needs to be made to 'un-collate' the items before collating them again. I have not done this yet, so they would not have been picked up this morning.

**Comment by ben-garside** [comment]
@VermaBSI do you have XCPIDs of the 12 items you would like re-collating please.

**Comment by VermaBSI** [comment]
CLAIMED list In the Collations tab in PROD:

1. All items still at 10.10 - XCP has collated nothing for these (i.e. no PDF either: error message is in the zips). I was able to obtain the PDFs from CoLos. If necessary please could these be removed to be discovered through the collation operation again.
2. All items at 10.15 - these are p2s that need to be re-discovered as p4s. I had downloaded their ISO XMLs yesterday (see issue #25)
Those are 10.20 are obviously fine to be picked up by the dummy send at 4pm
Many thanks

**Comment by ben-garside** [comment]
The following have been un-collated and force assigned to PL4 ready for collation on the next run:

XCP9952620
XCP8933341
XCP4754429
XCP3980527
XCP7239998
XCP3569203
XCP4582994
XCP6014456
XCP3954648
XCP6081370
XCP8946031
XCP0876927

**Comment by ben-garside** [comment]
These didnt work, i know why and i am re=processing them now.

**Comment by ben-garside** [comment]
We have made some chamges to the CDler application that seems to have fixed the PL2/4 issue (#26)

10 of them have been reallocated pipelines and collated as PL4s. 2 have not:

**XCP3569203** - has been allocated to PL7 as it is an IM (is an AMEND) project and the core BS is available in XML
**XCP9952620** - is still a PL 2 as it is an AM

**Comment by VermaBSI** [comment]
Thanks Ben, I have claimed these all and will look at them tomorrow, with view getting them sent tomorrow.

**Comment by VermaBSI** [comment]
Hi Ben,

It's great to see all those PL4s come in as PL4s now, i.e. as a result of CDldr, without any forced assignments - thanks! I've set the majority now to 10.20 so a good lot should go today :)

1. Regarding the two you mention:
XCP3569203 - can't actually find this in the system now (but if it's a PL7 then fine, it can join the list for Editorial here)
XCP9952620_30156028 - You're right, it's an AMD - we can let it down PL2 since there is no BS precursor in XML needed for PL7*
Instead though, since this is that silly case I explained above: if I supplied the core ISO for this would you be able to force assign this to P4? I've left it at 10.15
*(however, as I've raised before, ISO AMDs could still utilise the core ISO and then go down a combination of PL4+PL7 as the most efficient path - we can pick this development up at a later stage). 

2. Also, the following new ones should be PL4s as well, but are currently PL2s - these are also left at 10.15 for now:

XCP0876927_30329680
XCP4522564_30264414

Let me know if you need me to do anything.

3. Please could these rogue entries that have come through from CDldr be deleted from XCP:

XCP4049451_30065800 - 'PD IEC/TR 61010-3-043:2002 (DISKETTE)'
XCP5630554_30068604 - 'PD IEC/TR 61010-3-042:2002 (Disk)'
XCP8867091_30068495_p8.zip - 'PD IEC/TR 61010-3-041:2002 (DISK)'

4. Couple of items left at 10.10 in the CLAIMED list I am waiting for sister PL8s for (30009185, 30061587)

That's all!

Many thanks

**Comment by VermaBSI** [comment]
Hi Ben,

Apologies - just modifying the last list item above in my last comment, further to reviewing XCP this morning:

1. Items 30009185 and 30061587: PL8s are in for these, but not their sister PLs. And then, these PL8 collations have not found any source PDF (error text messages are in the collated zips).

This and those issues listed in my previous comment aside, we will need to do another send today for those items I am happy with and have set to 10.20.

Thanks :)

**Comment by ben-garside** [comment]
XCP3569203 - Sorry was assigned to me, have unassigned it. 

XCP9952620 - This needs to be talked about at a wider level and @odeclas needs to be involved as 'bending the rules' is not currently in scope. Either way it should be removed from this thread as this is not a system issue.

I would like it if @afproductions could have a look at these in regards to the CDler:

XCP0876927_30329680
XCP4522564_30264414

**Comment by VermaBSI** [comment]
Thanks Ben.

XCP9952620 - this would be a case for manual override, which I thought was a possibility we discussed at an earlier stage (see my comment above 'commented 29 days ago')?

**Comment by ben-garside** [comment]
@afproductions has look in to these:

30329680 - Is actually an AM/RV (@afproductions can explain in more detail) but at the end of the day the collation process is correct based on the data in the DWH. This is an issue to with the rules used.

30264414 - There is no ISO XML available so should be a PL2

**Comment by ben-garside** [comment]
in regards to 'manual override', it will need to be specified, agreed and raised as a feature request to be put in a future release.

**Comment by VermaBSI** [comment]
Okay sure - apologies, I thought we had already spoken about it (and so have it in my head that all that would be needed is for you/user to clear XCP of the current entry, I deposit any manually sourced files where they need to be, and that would make the system automatically collate and assign it again.)

**Comment by VermaBSI** [comment]
Yes sorry - following our meeting have just understood how for AMDs, XCP has been written only to be looking for the *previous BS version* to test for PL7, it would never be looking for any core ISO XML to test for PL4, so manually supplying the ISO XML would have no effect. The result would still be: as it fails test for PL7, it is a PL2.
Got it :)

(So yeh, good to have an option eventually to just manually send to cater for such cases.)
