### ISSUE TITLE
Lack of pipeline 4 assignment to newly published UPIs

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#26]
This is an ongoing issue with XCP.

ISO XMLs available from ISO's site are not being picked up internally, so some UPIs are not being assigned pipeline 4.

**Comment by ben-garside** [comment]
can some details be provided here please, with some examples etc. will make it easier to try and resolve.

Cheers.

**Comment by VermaBSI** [comment]
Hi Ben,

UPIs referenced in issue #25 are the on-going examples. 

But you can tell anyway which UPIs will always be relevant to this issue: if it has a standard ID ending 'ISO' (i.e. it is an ISO-based Material), and has been assigned pipeline 2, then it is an example. Any ISO-based Material should ideally be assigned pipeline 4, upon sourcing its ISO XML.

Now more have come in and I will need to manually source those from the ISO site (http://pod.iso.org/isostd/livelink?func=LL.getlogin&NextURL=%2Fisostd%2Flivelink%3F%3FRedirect%3D1). Will do this later in the week. They are in the CLAIMED list in the Collations Tab in PROD - have set them all to 10.15. 

I remember Adam saying the problem is that our internal repository of ISO Material is not kept up-to-date with what is available off ISO's site (URL above).

Thanks
Varun

**Comment by ben-garside** [comment]
This looked like it was an issue with the CDler application. Changes have been made and we should now be expecting a much higher percentage of correct  allocations. The only issue we should now have are due to the datafeed times but this is now believed to be an edge case, only time will tell.

**Comment by VermaBSI** [comment]
Okay Ben, thanks very much. Let's see.
