### ISSUE TITLE
No notification received for pipeline 1 item 30284748

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#27]
An email notification for Pipeline 1 item 30284748 (now stage 20.00) was never received. I only discovered it once I was in the XCP system, having been notified of it by the Product Manager.

**Comment by ben-garside** [comment]
It looks like this one was collated during the time that the notifications weren't working... I know that's not very helpful, and it might mean there are more :| Let me know if a list of all items in the system would be helpful to check against your records?

**Comment by VermaBSI** [comment]
If the list is what is already viewable in the Activity Tracker by filtering for pipeline 1, then I'll just check against that...otherwise if the list is bigger than than, then sure please do provide, thanks

**Comment by ben-garside** [comment]
They are deffo all in the system under one tab or another, i just dont know if every
item was listed in a notification at some point. I havej just done a check to make ure that all items are appearing in the lists and there was only one missing (XCP4252973) and i have added it in.

**Comment by VermaBSI** [comment]
Okay fine I will do a check later against the lists in the tabs. Hopefully going forward we'll get notifications for new stuff. You can close this and I can raise again as necessary.

**Comment by VermaBSI** [comment]
And thanks! :)

**Comment by VermaBSI** [comment]
Hi Ben,

I need to re-open this issue (having re-named it to cover such cases generally):

I didn't get any email notification for UPI 30302284 in the Activity Tracker (collated 4 days ago it said before I claimed it).

Thanks.

**Comment by ben-garside** [comment]
30302284 => XCP4312795
