### ISSUE TITLE
Please could the Innodata send list on automated email notifications be adjusted

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#30]
Hi Ben,

Innodata have just requested the following amendments in regards to who gets sent the email notifications for sends:

Pipeline 8 email notifications:
Please could the following email ID be added to the send list:
gcmontesclaros@INNODATA.COM

All other pipeline notifications:
Please could the following email ID be removed from the send list:
MMontano@INNODATA.COM

Many thanks!

**Comment by VermaBSI** [comment]
Hi Ben,

Innodata have also requested the following amendments in regards to who gets the email notifications for sends:

Pipeline 8 email notifications:
Please could the following email IDs be added to the send list:
Jaucian MJaucian@innodata.com 
ARQuismundo@innodata.com

Many thanks!

**Comment by ben-garside** [comment]
I have updated the list as requested, but please be aware this will not be in effect until it has been deployed.

**Comment by VermaBSI** [comment]
Hi Ben,

I know this is a pain - but Innodata have again requested another amendment in regards to who gets the email notifications for sends:

Pipeline 8 email notifications:
Please could the following email IDs be REMOVED from the send list:
JNemis@INNODATA.COM

Many thanks!
