### ISSUE TITLE
Internal send notification

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#34]
Add notification to sendItems on each run to notify internally that the process has run with nothing sent

**Comment by VermaBSI** [comment]
Hi, 

The content.operations Inbox has not yet been receiving these notifications (which I assume should be daily). The only notifications it did (used to) receive were regarding no items collated. However, now all collation notifications seem to have stopped altogether too.

**Comment by odeclas** [comment]
There was another ticket around the schedule send time - has XCP actually got send automation switched on @ben-Garside ?
