### ISSUE TITLE
allow filter setting to be set via URL

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#37]

**Comment by odeclas** [comment]
Can you explain the use case for this please?

**Comment by ben-garside** [comment]
Sure,

The idea here is that as add filters on the Activity Tracker URL parameters are added via JS, such as pipeline filter or feed id. Meaning that if i was to copy that URL I could go directly to that set of filters, kind of a crude save view type thing. I feel this might become useful as the more flows we put in the system the more noise there will be and if a user is only working on one (FM for example) they don't want to see the others, or have to reset the filters every time they login.

This is very much a backlog item, and is here more for a reminder and discussion point.
