### ISSUE TITLE
Fix/Update data dump

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#38]
Need to resurrect the data dump (dumpAudit.php). Handle reoccurring stages by showing start of first and end of last, also include a count to show number of repetitions.

**Comment by odeclas** [comment]
I wasn't clear that user details were available, could I have:

XCP ID
UPI
Designator
Type
Publication Date
Feed Name
Stream Id
Then a repeating set of fields
Stage identifier (eg 10:00)
Date of entry to stage
Name of first claimant
Date time of first claim
Name of last claimant
Date time of workflow action that moved it out of this stage
Number of times it was in this stage

If that is too complex, then I am happy to accept major stage codes to begin with (ie 0, 10, 20, 30 etc)

And in the short term I'm happy to work off a 'richer' version of the Excel dump that is already in place (and sort of working on Prod)

**Comment by ben-garside** [comment]
this is now in the test env (http://test.xcp.cs/) @odeclas can you please take a look.

**Comment by odeclas** [comment]
I am testing using XCP4754429. 
I cannot verify that the data captured in each column is correct.
For each stage you are reporting 4 dates - FirstDate (A), FirstAllocatedDate(B), LastDate(C) and LastAllocatedDate(D)

I would expect A to always be the earliest date of the four
I would expect C>A always
I would expect B>A by a few milliseconds for sticky allocation, and more for manual
I would expect C(or is it D) and (Next Stage)A to be the same 

Might be worth having a quick chat about this?

**Comment by ben-garside** [comment]
C/D are not the 'end' times, they are 'last' times. An activity currently has no end, for each stage the following data is stored:

- XCPID
- ACT (Activity)
- STATUS
- DATE (date this stage started)
- USER_ID (the user that started it)
- DATA (info)
- allocatedTo (user it was allocated to)
- allocatedOn (when it was allocated)
- allocatedBy (who allocated it)

The negative difference in the datetime for start and allocation (when sticky) is just due to the way in which the SQL Server handles the getdate() function, I will look in to changing this (#60).

### In the spreadsheet

A - XCP ID
B - UPI
C - Designator
D - Type
E - Publication Date
F - Feed Name
G - Stream Id

#### Then a repeating set of fields (using 00:99)
__Stage identifier (eg 00:99) - In header__
AD - Date of entry to stage
AF - Name of first claimant
AE - Date time of first claim
AI - Name of last claimant
n/a - Date time of workflow action that moved it out of this stage
AC - Number of times it was in this stage

Also:
AG - Date of last entry to stage
AH - Date of last claim

**Comment by odeclas** [comment]
Ok. Going to sign off for now and let Fergal change requirements if needed. Will treat B-A = negative number as 0 for now.
