### ISSUE TITLE
Create roles

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#45]
Create roles for OPE, EDITORIAL and ADMIN

this will limit which Activities that can be seen (make configurable)

**Comment by odeclas** [comment]
In the original stage documentation I talked of User, System, Editor User and Analyst User. Suggest that the easiest implementation is on the Activity Tracker view and simply show/hide stage tabs based on credentials. Not particularly elegant, but meets the immediate need.

A future requirement might be to restrict activities (sub-stage) to a role, but I think we can wait until we have a need for a tiered level of responsibility for that (eg Team Member, Team Leader, Team Manager).

**Comment by ben-garside** [comment]
Agreed, i was deffo just going to go for a dirty fix in the JS to only show tabs relevant to a group, will also add simple config to edit these settings.

**Comment by ben-garside** [comment]
New user types:

- Standard User
- Administrator
- System
- Editor
- Analyst

New roles:

- sysadmin
- admin
- editor
- analyst
- reporter

**Comment by odeclas** [comment]
Need login deets pls for UAT.

**Comment by odeclas** [comment]
Not sure if the username received via Lync was an AyeAye or not... Either way the user I was given is a standard user, not admin, so can't create other roles.

**Comment by ben-garside** [comment]
it is now :smile:

**Comment by ben-garside** [comment]
@odeclas can I remove the flag on this now?

**Comment by odeclas** [comment]
I have confirmed that roles can differ, and that roles have access to specified Activities only.  I have confirmed through log in that these roles stick and permissions stick.
