### ISSUE TITLE
Activity Manager dropdowns don't populate

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#55]
On the Activity Manager drop downs for Activity, Stage and Action, I cannot expose any data to select for any of the dropdowns (they just list their headers).

As such I am blocked from testing addition of Action Manager and Activity Manager flow.

Step:
- Log in as admin / adminadmin
- Click on Activity Manager
- Select a stage (eg 10:00)
- Observe dropdowns do not populate with activity / stage or action data

**Comment by ben-garside** [comment]
This is due to the use of cURL to find the available options , will either move the call to get data to the main page or rework it using JS (allowing the same process to be used)

**Comment by ben-garside** [comment]
getUrlContent($url) is the problem.  use Activity::listActions() directly
