### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#56]
allow commenting. (forced and free) could be tied to a stage change

**Comment by odeclas** [comment]
Having observed the Action Manager, I am happy that while less 'efficient' than having an overall comments system, it is probably simpler and better governance to have controlled comment fields that govern a specific workflow change. For example, always have an Action of 'Add Query Comment' to any activity flow that ends at 10:15, and have 'Query Resolution' as another Action on exit from 10:15.

Where this will work less well is if we are passing comments back and forth between roles in a loop - but as long as the users know this behaviour it might even be beneficial.

I have therefore set this as 'wontfix' and cleared the milestone. We can always review later.
