### ISSUE TITLE
PROD env not receiving collated content (compare to UAT env)

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#57]
The PROD env has stopped receiving new collations. All items currently 10.10 in the CLAIMED list in the Collation Tab in UAT, have not appeared in the Collation Tab PROD env for claiming.

**Comment by ben-garside** [comment]
I think the issue here is a bad reference to a table in the ``30_allocatePipeline_v0.1`` job (line 14). I have removed and currently re-running the process.

**Comment by ben-garside** [comment]
Looks like that fixed it, the following new item were collated:

- 30047368
- 30256178
- 30260135
- 30264426
- 30297755
- 30329680

Can you please confirm this @VermaBSI?

**Comment by VermaBSI** [comment]
Thanks, I can confirm the same.
