### ISSUE TITLE
Activity Tracker : All claimed items - Update status within stage not reflected to user

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#6]
When changing a status that does not move it to another queue, the status does not refresh on the row item, and the Refresh icon appears to only refresh the count at the top of the tracker.

Entering the page again will make the item show the correct status (ie refreshed).

**Comment by ben-garside** [comment]
I am struggling to reproduce the behaviour of the status not refreshing, could you provide more details please

**Comment by ben-garside** [comment]
fixed in 7df2e65bbc28ba9e837bcd71c93c517185d8dad7 testing again on various browsers
