### ISSUE TITLE
Action not triggering between major stage

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#61]
I have added an action to 10:25 that fires fine to other 10:x stages but not to 20:x stage.

Similarly there is a 30:99 to 10:10 activity that does not trigger its action.

**Comment by ben-garside** [comment]
I am unable to recreate the issues that you are having. _I assume you are referring to 10:15 not 10:25 as this stage does not exist._

 - There is currently no 10:15 -> 10:* action or rule set up.
 - The change 10:15 -> 00:99 triggers an action as expected
 - There is no action set up for 30:99 -> 10:10

Could you provide some more information including the XCPID of the item you are using to test.

Cheers.
