### ISSUE TITLE
Allow re-collation of items

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#65]

**Comment by VermaBSI** [comment]
The following test procedure of a few items from different pipelines (see CLAIMED list in PreXCP Tab) has produced the following result:
1. Enter the detail page of an item at stage 0.99 in PreXCP tab
2. Attempt to download by clicking the zip package link the data suggests HAS been collated (then why stage 0.99?)
3. A blank screen results (no download - as nothing actually collated presumably).
4. Go back to item detail page
5. Now press re-collate content
6. Once done, Collated files data updates accordingly
7. The zip package now actually downloads successfully when you click the link (i.e. successful collation).
8. The item however still stays at 0.99 in the PreXCP tab, and doesn't move to 10.10. Is this something that can only happen with stage rules and user input? It would be good if the system could automatically push on to stage 10.10

So pressing re-collation successfully re-collates the files, but the item details before the re-collate action confusingly suggest a collation has already been made - and then once files are successfully collated, the item stays at stage 0.99.

**Comment by VermaBSI** [comment]
I've just seen that steps 1.-3. above are happening even for items at stages 10.10 and onwards through the whole system, so I am really confused now.

**Comment by ben-garside** [comment]
Yes, moving from 00:99 is currently a manual process. I understand the need for automation, i suggest raising an issue for future discussion.

Also, you are correct when the screen goes blank on clicking the download link it means that the system could not find the actual file on the server (i will raise a bug to provide feedback, but it should never really happen) this is happening in UAT because of the copying of items over from the PRD site, it should not happen in PRD. I will keep an eye out going forward. It is easily remedied by re-collating the files again.

**Comment by VermaBSI** [comment]
Thanks - the main concern is not the blank screen in itself, but the fact that it suggests a successful collation already has been made with a live zip-package download link, which is wrong if it is going to result in a blank screen.

And also that a blank screen is resulting for items already collated and moved forward in the system (items at stages 10.10 and also 30.00, I remember I tried). Ideally we don't want to have to press re-collate at later stages.
