### ISSUE TITLE
Manual inclusion

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#66]
We occasionally get asked to manually include UPIs in a product feed that do not meet the nominated criteria for the feed. We need a method to include this/these UPIs against that feed.

Internally, the workings are different, but from a UI perspective I am expecting something similar to the 'Exclusions' list.

Another feature that this would enable is to have a 'Test' feed, into which we could put entirely arbitrary UPIs into, to aid development and test various features. I will request the creation of Test feed in a separate ticket.

**Comment by odeclas** [comment]
To simplify testing - it would be useful to have a 'Test' feed on UAT. Can this be added (no collation tasks required).

**Comment by odeclas** [comment]
Issue 1 - Added a UPI to CN Term Mapping feed (30296276). 
Received success message with XCP ID - 7661132. 
Clicked link - no such ID exists
Can't find using search at top or in activity manager for either UPI or XCP ID.

**Comment by VermaBSI** [comment]
Good news: issue #114 - which has become feature request #120 - aside, this has worked for a UPI that represents a real, full BSI Project and so passes all DWH validation. Fortunately the PM for EC+ asked me to add an old backlist Material for conversion which I just added manually in XCP UAT successfully, with pipeline allocation and collation all correctly done:

Item XCP5250854_30275641

It would be good to test this for a more complex collation, i.e. a pipeline 4, but no idea when a manual inclusion request for that will come along, so best to consider this done and closed I think.

**Comment by VermaBSI** [comment]
Hi I've just realised that sister p8 items are not being created for anything manually added to CN feed (p 1-7).

This can be fixed in v1.4 UAT.

**Comment by ben-garside** [comment]
Please can you raise a new issue for this.

Thanks,
