### ISSUE TITLE
Re-collation

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#67]
We have found that sometimes content downloader has not executed in the way we anticipated (or know) it should have done, and so the wrong pipeline has been allocated to an XCP item based on missing content.

We need some method of sending items back to 00.XX and re-triggering the collation process. The most likely precursor is 10:15 Query Package.

**Comment by ben-garside** [comment]
Current process used:
```
declare @xcpid as varchar(10)
declare @stream as int

set @xcpid = ''
set @stream = ''

 -- CHANGE PIPELINE
UPDATE [STREAM_ALLOCATION] set STREAM_ID = @stream where XCP_ID = @xcpid

-- -- REMOVE COLLATED FILES
SELECT TOP 1 'DEL ' + [FILE_LOCATION] FROM FILE_COLLATION WHERE XCP_ID = @xcpid
DELETE FROM [FILE_COLLATION] WHERE XCP_ID = @xcpid

-- UPDATE AUDIT
INSERT INTO [dbo].[ACT_AUDIT] ([XCPID],[ACT],[STATUS],[DATE],[USER_ID],[DATA])
     VALUES (@xcpid,10,15,getdate(),1,'Changing STREAM_ID due to error in collation')
```

**Comment by ben-garside** [comment]
this will be effected by #64

**Comment by ben-garside** [comment]
removed from v1.3

**Comment by ben-garside** [comment]
as part of #105 in-app collation is now possible, this will just be a case of re-using in UI

**Comment by VermaBSI** [comment]
Is this not the same as #65 ? Will leave with you to close if is.
