### ISSUE TITLE
Typo - Activity tracking - 'Convertion'

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#68]
Both on the Activity Tracking coloured tabs and on the Manage Activity flow the major stage 'Conversion' is misspelt 'Convertion'.

This is on both Prod and UAT.

**Comment by ben-garside** [comment]
This is in the configuration not in the code, this will be able to change via the Activity manager in v1.2.2

**Comment by odeclas** [comment]
Signed off having validated on UAT.
