### ISSUE TITLE
Add 'skip if populated' to Action Manager

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#71]
Allow actions (or more specifically, fields within actions) to be skipped if they have already been filled in. This is primarily intended for BATCH_DATA fields, such as TAT / Quote

**Comment by VermaBSI** [comment]
Hi, because of #135 I cannot set the right rule to test this issue.

**Comment by VermaBSI** [comment]
Just adding Matt H so he's aware of all issues for next XCP meeting: @hendersm

**Comment by VermaBSI** [comment]
This is now working too with the items from the latest test sends :)
