### ISSUE TITLE
Admin > Manage Activity Flow : No configuration controls available

### ISSUE THREAD

**Issue by afproductions** [ben-garside/XCP#8]
An admin user currently can't configure milestones 30, 40, etc when there is no previous configuration in place (i.e. not form controls to add additional configurations)

**Comment by ben-garside** [comment]
Added the ability to add a new stage, this will then guide the user to that stages page to add fields

**Comment by odeclas** [comment]
Happy to sign off that you can add a new Stage to the Activity list, that Stage is incorporated into standard Action and Activity flows.
