### ISSUE TITLE
No new collations seen for a little while

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#93]
Hi Ben,

New items in XCP PROD appear to have dried up - there have been no new collations to check and send since the last send on 19/10/2015. 

This doesn't seem right given that a pipeline report I manually downloaded recently indicates items reached PUBL on 21/10 and 22/10, 2015.

Please could you have a quick check that the collation tool is functioning properly or anything else that could be the cause is in order?

Many thanks

**Comment by ben-garside** [comment]
This has been fixed.
