### ISSUE TITLE
Extension to Manual Inclusion

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#94]

**Comment by odeclas** [comment]
Relating to issue #66

**Comment by odeclas** [comment]
Please allow Manual Inclusion to determine at what Stage (number) the items should enter the Feed.
Validate that the stage exists for the feed.

(I would expect us to enter most items at stage 20:20 - conversion completed)

**Comment by VermaBSI** [comment]
This was successfully achieved as part of the resolution and closure of issue #66.
