### ISSUE TITLE
No new collations seen for a little while

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#96]
Apologies if this was already raised as an issue (can't find it on GitHub under CLOSED/DONE):

Since the send to Innodata on 10/11/2015, XCP has not discovered and delivered any further content to Innodata for conversion. Everyday I have been getting notifications informing no collations have been made. 

This seems wrong. For example, a forecast report I downloaded early in the month indicated the following all as PUBL which have yet to come through (and more not listed have since become PUBL through the course of this month, a check on BS Shop confirms):

30173424
30333203
30152117
30166680
30169327
30172485
30293475
30293489

NB. These are all CEN or IEC.

Please could this be seen to asap, as content flow to products is drying up.

Many thanks!

**Comment by ben-garside** [comment]
Closing this issue as it is now incorporated by #97
