### ISSUE TITLE
Items incorrectly being assigned to PL100 (no file in index)

### ISSUE THREAD

**Issue by ben-garside** [ben-garside/XCP#97]
_This incorporates #96 and #53._

The problem here is that item during the collation and allocation process (the 'collation tool') are being assigned to the pseudo pipeline of 100 (all PL 90 and above are errors).

These items should be assigned correctly as the content is there, i believe this is due to a change that was make that increased the error codes (pseudo pipelines) from 90-99 to 90-111.

As it appears to be happening to all new items this is stopping content from progressing through the system.

**Comment by ben-garside** [comment]
I have found the issue causing this and i am working on a fix

**Comment by ben-garside** [comment]
@VermaBSI, This has now been fixed, it was an error in some SQL used in the collation tool, this will be mitigated once the collation etc in in app.

any-who, now 37 items should have been collated, here is a list:

https://gist.github.com/ben-garside/9d593f689635bf8cff15

let me know if you still believe this to be an issue, otherwise i will close it.

**Comment by VermaBSI** [comment]
Hi Ben,

Thanks for solving that content block. I've checked UPIs expected and all are now there except the PL 2 for 30333203.

**Comment by VermaBSI** [comment]
A search on that UPI brings up PL 8 and PL 100 still.

**Comment by ben-garside** [comment]
Is all the content for XCP0735299(30333203) in the archive?

**Comment by VermaBSI** [comment]
This being an IEC originating Material adopted as by CLC as an EN, we don't want to source any ISO STS XML for it that may/may not be in the RAW ISO STS archive.

Regardless of that, the BS PDF under UPI 30333203 should be source-able for PL2 assignment - as it was sourced for this Material's PL8.
